version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-vol:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - default

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    env_file:
      - .env
    environment:
      - PMA_HOST=${MYSQL_HOST}
      - PMA_PORT=3306
      #- PMA_USER=${MYSQL_USER}
      #- PMA_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - default

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.0-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOST}:3306
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE}
    volumes:
      - wordpress-vol:/var/www/html
    networks:
      - default

  webserver:
    depends_on:
      - wordpress
    image: nginx:stable-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"    
    volumes:
      - wordpress-vol:/var/www/html
      - ./nginx-config:/etc/nginx/conf.d
      - certbot-etc:/etc/letsencrypt
    networks:
      - default

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - wordpress-vol:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email mohamadrezajavid9@gmail.com --agree-tos --no-eff-email --staging -d jlinux.ir -d www.jlinux.ir

volumes:
  db-vol:
    name: db_vol
  wordpress-vol:
    name: wordpress_vol
  certbot-etc:
    name: certbot_etc_vol

networks:
  default:
    name: app_net